apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-runnerdeploy2
spec:
  replicas: 4
  template:
    spec:
      repository: mkjost0/gem5-actions

# add image (new image with summerwind and gem5 info)
