name: Github Artifacting Tests
run-name: Testing artifact usage
#  https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
on: [push]
  # schedule:
  #   - cron:  '0 * * 1 *' # this only runs once a year, for files that aren't being tested

# This file is an example of using artifacts in different runs, for us to utilize in
# separating jobs amongst different runners
jobs:
  Test-Upload:
    runs-on: [self-hosted, linux, x64, build]
    # running container with only a single arguement passes the image being used
    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest

    steps:
    # checks out repository, should be more useful when
    # running checks on changed files
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build and run gem5
        run: |
          scons build/ALL/gem5.opt -j $(nproc)

      - uses: actions/upload-artifact@v3
        with:
          name: gem5-artifact
          path: build/ALL

      - run: echo "🍏 This job's status is ${{ job.status }}."

  Test-Download:
    runs-on: [self-hosted, linux, x64, build]
    # running container with only a single arguement passes the image being used
    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
    needs: Test-Upload

    steps:
    # checks out repository, should be more useful when
    # running checks on changed files
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v3
        with:
          name: gem5-artifact
          path: build/ALL

      - name: Display structure of downloaded files
        run: ls -R
        # working-directory: build/X86

      # double checking that steps are run chronologically
      - name: Run gem5 separately (memory_traffic.py)
        run: |
          chmod u+x build/ALL/gem5.opt
          ./main.py run --length=long gem5/cpu_tests/ --skip-build

      - run: echo "🍏 This job's status is ${{ job.status }}."
