# This workflow runs all of the very-long tests within main.py

name: Running gpu tests
run-name: ${{ github.actor }} is running the gpu tests


on:
  # Runs every Sunday from 7AM UTC
  # push:
  schedule:
    - cron:  '00 7 * * 6'

jobs:
  build-gem5:
    runs-on: [self-hosted, linux, x64, build]
    container: mkjost/testing-gpu-image:latest
    outputs:
      build-name: ${{ steps.artifact-name.outputs.name }}
    steps:
      - uses: actions/checkout@v3
        with:
          # Scheduled workflows run on the default branch by default. We
          # therefore need to explicitly checkout the develop branch.
          ref: develop
      - id: artifact-name
        run: echo "name=$(date +"%Y-%m-%d_%H.%M.%S")-ALL" >> $GITHUB_OUTPUT
      - name: Build gem5
        run: |
          scons build/GCN3_X86/gem5.opt -j $(nproc) --ignore-style

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.artifact-name.outputs.name }}
          path: build/ALL/gem5.opt
          retention-days: 5
      - run: echo "This job's status is ${{ job.status }}."

