# This workflow runs all of the very-long tests within main.py

name: Running gpu tests
run-name: ${{ github.actor }} is running the gpu tests


on:
  # Runs every Sunday from 7AM UTC
  push:
  # schedule:
  #   - cron:  '00 7 * * 6'

jobs:
  build-gem5:
    runs-on: [self-hosted, linux, x64, build]
    container: mkjost/testing-gpu-image:latest
    outputs:
      build-name: ${{ steps.artifact-name.outputs.name }}
    steps:
      - uses: actions/checkout@v3
        with:
          # Scheduled workflows run on the default branch by default. We
          # therefore need to explicitly checkout the develop branch.
          ref: develop
      - id: artifact-name
        run: echo "name=$(date +"%Y-%m-%d_%H.%M.%S")-ALL" >> $GITHUB_OUTPUT
      - name: checkout gem5 resources
        working-directory: ${{ github.workspace }}
        run: |
          git clone https://gem5.googlesource.com/public/gem5-resources
          cd gem5-resources
          git checkout develop
      - name: Test gpu tests (just lulesh)
        working-directory: ${{ github.workspace }}
        run: scons build/GCN3_X86/gem5.opt -j4 --ignore-style || rm -rf build && scons build/GCN3_X86/gem5.opt -j4 --ignore-style
      - name: continue
        working-directory: ${{ github.workspace }}/util/m5
        run: |
          export TERM=xterm-256color
          scons build/x86/out/m5
      - name: continueee
        working-directory: ${{ github.workspace }}/gem5-resources/src/gpu/lulesh
          make
      - name: sdoklfj
        working-directory: ${{ github.workspace }}
        run: build/GCN3_X86/gem5.opt configs/example/apu_se.py -n3 --mem-size=8GB --reg-alloc-policy=dynamic --benchmark-root="gem5-resources/src/gpu/lulesh/bin" -c lulesh




      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: ${{ steps.artifact-name.outputs.name }}
      #     path: build/ALL/gem5.opt
      #     retention-days: 5
      # - run: echo "This job's status is ${{ job.status }}."

