# This workflow runs all of the tests within main.py, and unittests

name: Running main.py
run-name: ${{ github.actor }} is running main.py tests

on: [push]
  # schedule:
  #   - cron:  '0 0 * * *'

jobs:
  build-gem5:
    runs-on: [self-hosted, linux, x64, build]
    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
    outputs:
      build-name: ${{ steps.artifact-name.outputs.name }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: artifact-name
        run: echo "name=$(date +"%Y-%m-%d_%H.%M.%S")-artifact" >> $GITHUB_OUTPUT
      - name: Build gem5
        run: |
          scons build/ALL/gem5.opt -j $(nproc)
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.artifact-name.outputs.name }}
          path: build/ALL/gem5.opt
      - run: echo "This job's status is ${{ job.status }}."

  # This runs the unit tests for the build/ALL/unittests.debug build.
  unittests-all-debug:
    runs-on: [self-hosted, Linux, X64, run]
    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: ALL/unittests.debug UnitTests
      run: scons build/ALL/unittests.debug

  # This runs the unit tests for the build/ALL/unittests.fast build.
  unittests-all-fast:
    runs-on: [self-hosted, Linux, X64, run]
    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: ALL/unittests.fast UnitTests
      run: scons build/ALL/unittests.fast

  # testlib-quick: #runs all quick tests, could be sorted if needed
  #   runs-on: [self-hosted, Linux, X64, run]
  #   container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
  #   needs: build-gem5
  #   timeout-minutes: 1440 # 24 hours
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: actions/download-artifact@v3
  #     with:
  #       name: ${{ env.artifact-name }}
  #       path: build/ALL/gem5.opt
  #   - run: chmod u+x build/ALL/gem5.opt
  #   - name: The TestLib CI Tests
  #     working-directory: ${{ github.workspace }}/tests
  #     run: ./main.py run --length=quick --skip-build -vv
  #   - run: echo "This job's status is ${{ job.status }}."

  testlib-long-arm-boot-tests:
    runs-on: [self-hosted, Linux, X64, run]
    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
    needs: build-gem5
    timeout-minutes: 1440 # 24 hours
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: ${{needs.build-gem5.outputs.build-name}}
        path: build/ALL
    - run: chmod u+x build/ALL/gem5.opt
    - name: long arm-boot-tests
      working-directory: ${{ github.workspace }}/tests
      run: ./main.py run gem5/arm-boot-tests --length=long --skip-build -vv
    - run: echo "This job's status is ${{ job.status }}."

  testlib-long-fs:
    runs-on: [self-hosted, Linux, X64, run]
    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
    needs: build-gem5
    timeout-minutes: 1440 # 24 hours
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: ${{needs.build-gem5.outputs.build-name}}
        path: build/ALL
    - run: chmod u+x build/ALL/gem5.opt
    - name: long fs
      working-directory: ${{ github.workspace }}/tests
      run: ./main.py run gem5/fs --length=long --skip-build -vv
    - run: echo "This job's status is ${{ job.status }}."

  testlib-long-gem5_library_example_tests:
    runs-on: [self-hosted, Linux, X64, run]
    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
    needs: build-gem5
    timeout-minutes: 1440 # 24 hours
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: ${{needs.build-gem5.outputs.build-name}}
        path: build/ALL
    - run: chmod u+x build/ALL/gem5.opt
    - name: long gem5_library_example_tests
      working-directory: ${{ github.workspace }}/tests
      run: ./main.py run gem5/gem5_library_example_tests --length=long --skip-build -vv
    - run: echo "This job's status is ${{ job.status }}."

  testlib-long-gpu:
    runs-on: [self-hosted, Linux, X64, run]
    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
    needs: build-gem5
    timeout-minutes: 1440 # 24 hours
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: ${{needs.build-gem5.outputs.build-name}}
        path: build/ALL
    - run: chmod u+x build/ALL/gem5.opt
    - name: long gpu
      working-directory: ${{ github.workspace }}/tests
      run: ./main.py run gem5/gpu --length=long --skip-build -vv
    - run: echo "This job's status is ${{ job.status }}."

  testlib-long-insttest_se:
    runs-on: [self-hosted, Linux, X64, run]
    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
    needs: build-gem5
    timeout-minutes: 1440 # 24 hours
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: ${{needs.build-gem5.outputs.build-name}}
        path: build/ALL
    - run: chmod u+x build/ALL/gem5.opt
    - name: long insttest_se
      working-directory: ${{ github.workspace }}/tests
      run: ./main.py run gem5/insttest_se --length=long --skip-build -vv
    - run: echo "This job's status is ${{ job.status }}."

  # testlib-long-kvm-fork-tests:
  #   runs-on: [self-hosted, Linux, X64, run]
  #   container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
  #   needs: build-gem5
  #   timeout-minutes: 1440 # 24 hours
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: actions/download-artifact@v3
  #     with:
  #       name: ${{ env.artifact-name }}
  #       path: build/ALL/gem5.opt
  #   - run: chmod u+x build/ALL/gem5.opt
  #   - name: long kvm-fork-tests
  #     working-directory: ${{ github.workspace }}/tests
  #     run: ./main.py run gem5/kvm-fork-tests --length=long --skip-build -vv
  #   - run: echo "This job's status is ${{ job.status }}."

  # testlib-long-kvm-switch-tests:
  #   runs-on: [self-hosted, Linux, X64, run]
  #   container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
  #   needs: build-gem5
  #   timeout-minutes: 1440 # 24 hours
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: actions/download-artifact@v3
  #     with:
  #       name: ${{ env.artifact-name }}
  #       path: build/ALL/gem5.opt
  #   - run: chmod u+x build/ALL/gem5.opt
  #   - name: long kvm-switch-tests
  #     working-directory: ${{ github.workspace }}/tests
  #     run: ./main.py run gem5/kvm-switch-tests --length=long --skip-build -vv
  #   - run: echo "This job's status is ${{ job.status }}."

  testlib-long-learning_gem5:
    runs-on: [self-hosted, Linux, X64, run]
    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
    needs: build-gem5
    timeout-minutes: 1440 # 24 hours
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: ${{needs.build-gem5.outputs.build-name}}
        path: build/ALL
    - run: chmod u+x build/ALL/gem5.opt
    - name: long learning_gem5
      working-directory: ${{ github.workspace }}/tests
      run: ./main.py run gem5/learning_gem5 --length=long --skip-build -vv
    - run: echo "This job's status is ${{ job.status }}."

  testlib-long-m5_threads:
    runs-on: [self-hosted, Linux, X64, run]
    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
    needs: build-gem5
    timeout-minutes: 1440 # 24 hours
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: ${{needs.build-gem5.outputs.build-name}}
        path: build/ALL
    - run: chmod u+x build/ALL/gem5.opt
    - name: long m5_threads
      working-directory: ${{ github.workspace }}/tests
      run: ./main.py run gem5/m5_threads --length=long --skip-build -vv
    - run: echo "This job's status is ${{ job.status }}."

  testlib-long-memory:
    runs-on: [self-hosted, Linux, X64, run]
    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
    needs: build-gem5
    timeout-minutes: 1440 # 24 hours
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: ${{needs.build-gem5.outputs.build-name}}
        path: build/ALL
    - run: chmod u+x build/ALL/gem5.opt
    - name: long memory
      working-directory: ${{ github.workspace }}/tests
      run: ./main.py run gem5/memory --length=long --skip-build -vv
    - run: echo "This job's status is ${{ job.status }}."

  testlib-long-multi_isa:
    runs-on: [self-hosted, Linux, X64, run]
    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
    needs: build-gem5
    timeout-minutes: 1440 # 24 hours
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: ${{needs.build-gem5.outputs.build-name}}
        path: build/ALL
    - run: chmod u+x build/ALL/gem5.opt
    - name: long multi_isa
      working-directory: ${{ github.workspace }}/tests
      run: ./main.py run gem5/multi_isa --length=long --skip-build -vv
    - run: echo "This job's status is ${{ job.status }}."

  testlib-long-replacement-policies:
    runs-on: [self-hosted, Linux, X64, run]
    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
    needs: build-gem5
    timeout-minutes: 1440 # 24 hours
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: ${{needs.build-gem5.outputs.build-name}}
        path: build/ALL
    - run: chmod u+x build/ALL/gem5.opt
    - name: long replacement-policies
      working-directory: ${{ github.workspace }}/tests
      run: ./main.py run gem5/replacement-policies --length=long --skip-build -vv
    - run: echo "This job's status is ${{ job.status }}."

  testlib-long-riscv-boot-tests:
    runs-on: [self-hosted, Linux, X64, run]
    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
    needs: build-gem5
    timeout-minutes: 1440 # 24 hours
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: ${{needs.build-gem5.outputs.build-name}}
        path: build/ALL
    - run: chmod u+x build/ALL/gem5.opt
    - name: long riscv-boot-tests
      working-directory: ${{ github.workspace }}/tests
      run: ./main.py run gem5/riscv-boot-tests --length=long --skip-build -vv
    - run: echo "This job's status is ${{ job.status }}."

  testlib-long-stdlib:
    runs-on: [self-hosted, Linux, X64, run]
    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
    needs: build-gem5
    timeout-minutes: 1440 # 24 hours
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: ${{needs.build-gem5.outputs.build-name}}
        path: build/ALL
    - run: chmod u+x build/ALL/gem5.opt
    - name: long stdlib
      working-directory: ${{ github.workspace }}/tests
      run: ./main.py run gem5/stdlib --length=long --skip-build -vv
    - run: echo "This job's status is ${{ job.status }}."

  testlib-long-x86-boot-tests:
    runs-on: [self-hosted, Linux, X64, run]
    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
    needs: build-gem5
    timeout-minutes: 1440 # 24 hours
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: ${{needs.build-gem5.outputs.build-name}}
        path: build/ALL
    - run: chmod u+x build/ALL/gem5.opt
    - name: long x86-boot-tests
      working-directory: ${{ github.workspace }}/tests
      run: ./main.py run gem5/x86-boot-tests --length=long --skip-build -vv
    - run: echo "This job's status is ${{ job.status }}."

  testlib-very-long-gem5_library:
    runs-on: [self-hosted, Linux, X64, run]
    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
    needs: build-gem5
    timeout-minutes: 1440 # 24 hours
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: ${{needs.build-gem5.outputs.build-name}}
        path: build/ALL
    - run: chmod u+x build/ALL/gem5.opt
    - name: very-long gem5_library_example_tests
      working-directory: ${{ github.workspace }}/tests
      run: ./main.py run gem5/gem5_library_example_tests --length=very-long --skip-build -vv
    - run: echo "This job's status is ${{ job.status }}."

  testlib-very-long-gem5_resources:
    runs-on: [self-hosted, Linux, X64, run]
    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
    needs: build-gem5
    timeout-minutes: 1440 # 24 hours
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: ${{needs.build-gem5.outputs.build-name}}
        path: build/ALL
    - run: chmod u+x build/ALL/gem5.opt
    - name: very-long gem5-resources
      working-directory: ${{ github.workspace }}/tests
      run: ./main.py run gem5/gem5-resources --length=very-long --skip-build -vv
    - run: echo "This job's status is ${{ job.status }}."

  testlib-very-long-parsec-benchmarks:
    runs-on: [self-hosted, Linux, X64, run]
    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
    needs: build-gem5
    timeout-minutes: 1440 # 24 hours
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: ${{needs.build-gem5.outputs.build-name}}
        path: build/ALL
    - run: chmod u+x build/ALL/gem5.opt
    - name: very-long parsec-benchmarks
      working-directory: ${{ github.workspace }}/tests
      run: ./main.py run gem5/parsec-benchmarks --length=very-long --skip-build -vv
    - run: echo "This job's status is ${{ job.status }}."

  testlib-very-long-x86-boot-tests:
    runs-on: [self-hosted, Linux, X64, run]
    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
    needs: build-gem5
    timeout-minutes: 1440 # 24 hours
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: ${{needs.build-gem5.outputs.build-name}}
        path: build/ALL
    - run: chmod u+x build/ALL/gem5.opt
    - name: very-long x86-boot-tests
      working-directory: ${{ github.workspace }}/tests
      run: ./main.py run gem5/x86-boot-tests --length=very-long --skip-build -vv
    - run: echo "This job's status is ${{ job.status }}."
