name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: [self-hosted, linux, x64]
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v3
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} events."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          python -m pip install scons
          pip install -r requirements.txt
          pip install python-config
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          apt install zlib1g zlib1g-dev

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v19

      - name: Install black and reorder-python-imports
        run: pip install black reorder-python-imports

      - name: Black and Sort changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo $file
            if [[ $file == *.py ]]; then
              black $file --check
              reorder-python-imports $file
            fi
          done

      - name: build gem5
        run: python3 $(which scons) build/ALL/gem5.opt -j 24 PYTHON_CONFIG=/usr/bin/python3-config 
      - name: run x86 tests wit initial build
        run: |
              cd tests
              ./main.py run gem5/x86-boot-tests
      - run: echo "🍏 This job's status is ${{ job.status }}."
