name: docker
run-name: docker test
#  allows us to repeat this daily at 2am
#  https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

on: [push]
# on:
#   schedule:
#     - cron:  '0 2 * * *'

# This is a WIP file for recreating weekly.sh
jobs:
  Docker:
    runs-on: [self-hosted, linux, x64]
    # running container with only a single arguement passes the image being used
    # container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
    timeout-minutes: 4320 # 3 days
    env:
      GEM5ROOT_PATH: /runner/_work/gem5-actions/gem5-actions

    steps:
    # checks out repository, should be more useful when
    # running checks on changed files
      # - uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 0
      # - name: Set up Docker Buildx
      #   # uses: docker/setup-buildx-action@v2
      #   uses: docker/setup-buildx-action@v1
      #   with:
      #     version: latest
      #     endpoint: builders
      - name: test echo
        # run: echo ${{ env.GEM5ROOT_PATH }}
        run: echo ${GEM5ROOT_PATH}
      # - run: docker context create mycontext
      # - run: docker context use mycontext
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      #   with:
      #     buildkitd-flags: --debug
      #     endpoint: mycontext
        # with:
        #   context: ./gem5-resources/src/gpu/halo-finder 
        #   # file: gem5-resources/src/gpu/halo-finder 
        #   tags: hacc-test-weekly
        #   # build-args: |
        #   #     "NPM_TOKEN=${{ secrets.TOKEN }}"
        #   push: true

      - run: echo "🍏 This job's status is ${GEM5ROOT_PATH}."

