name: docker
run-name: docker test
#  allows us to repeat this daily at 2am
#  https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

on: [push]
# on:
#   schedule:
#     - cron:  '0 2 * * *'

# This is a WIP file for recreating weekly.sh
jobs:
  Docker1:
    runs-on: [self-hosted, linux, x64]
    # running container with only a single arguement passes the image being used
    # container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
    timeout-minutes: 4320 # 3 days
    env:
      GEM5ROOT_PATH: ${pwd}}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: start gpu tests
        run: |
          echo ${GEM5ROOT_PATH}

  