name: GitHub Actions gem5 Test Run
run-name: Running an X86 test
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: [self-hosted, linux, x64]
    # running container with only a single arguement passes the image being used
    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest

    steps:
    # checks out repository, should be more useful when
    # running checks on changed files
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build and run gem5
        run: |
          scons build/X86/gem5.opt -j $(nproc)

      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: assets-for-download
          path: build/X86

      # double checking that steps are run chronologically
      - name: Run gem5 separately (memory_traffic.py)
        run: |
          build/X86/gem5.opt configs/learning_gem5/part1/simple.py

      - run: echo "🍏 This job's status is ${{ job.status }}."
