name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} events."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: check info
        run: |
              cat /proc/cpuinfo
              if [ -f /.dockerenv ]; then
                echo "I'm inside matrix ;(";
              else
                echo "I'm living in real world!";
              fi
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          python -m pip install scons
          pip install python-config
          # unset PYTHONPATH
          # unset PYTHONHOME
          # export PYTHONPATH='/home/mkjost/.local/lib/python3.8/site-packages'
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v19

      - name: Install black and reorder-python-imports
        run: pip install black reorder-python-imports

      - name: Black and Sort changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo $file
            if [[ $file == *.py ]]; then
              black $file --check
              reorder-python-imports $file
            fi
          done

      - name: build gem5
        run: |
          #     echo "nothing happens here"
              scons build/ALL/gem5.opt -j 24
          #     # scons build/ALL/gem5.fast -j4 --no-compress-debug --ignore-style
      - name: run x86 tests without initial build
        run: |
              cd tests
              ./main.py run gem5/x86-boot-tests -j24
          #     # ./main.py run -j4 -t4 gem5 -vv && scons -C .. --no-compress-debug --ignore-style build/ARM/unittests.opt
          # gcr.io/gem5-test/ubuntu-20.04_all-dependencies:v22-0
      - run: echo "🍏 This job's status is ${{ job.status }}."
